//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.05 at 10:20:43 AM CET 
//


package src;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Head.Categories }
     * 
     */
    public Recipeml.Recipe.Head.Categories createRecipemlRecipeHeadCategories() {
        return new Recipeml.Recipe.Head.Categories();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Ingredients }
     * 
     */
    public Recipeml.Recipe.Ingredients createRecipemlRecipeIngredients() {
        return new Recipeml.Recipe.Ingredients();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Ingredients.IngDiv.Ing }
     * 
     */
    public Recipeml.Recipe.Ingredients.IngDiv.Ing createRecipemlRecipeIngredientsIngDivIng() {
        return new Recipeml.Recipe.Ingredients.IngDiv.Ing();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Ingredients.IngDiv }
     * 
     */
    public Recipeml.Recipe.Ingredients.IngDiv createRecipemlRecipeIngredientsIngDiv() {
        return new Recipeml.Recipe.Ingredients.IngDiv();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Directions }
     * 
     */
    public Recipeml.Recipe.Directions createRecipemlRecipeDirections() {
        return new Recipeml.Recipe.Directions();
    }

    /**
     * Create an instance of {@link Recipeml }
     * 
     */
    public Recipeml createRecipeml() {
        return new Recipeml();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Ingredients.IngDiv.Ing.Amt }
     * 
     */
    public Recipeml.Recipe.Ingredients.IngDiv.Ing.Amt createRecipemlRecipeIngredientsIngDivIngAmt() {
        return new Recipeml.Recipe.Ingredients.IngDiv.Ing.Amt();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe }
     * 
     */
    public Recipeml.Recipe createRecipemlRecipe() {
        return new Recipeml.Recipe();
    }

    /**
     * Create an instance of {@link Recipeml.Recipe.Head }
     * 
     */
    public Recipeml.Recipe.Head createRecipemlRecipeHead() {
        return new Recipeml.Recipe.Head();
    }

}
